### ISSUE TITLE
[MAP] cannot load .cgns file

### ISSUE THREAD

**Issue by ZekiFayes** [pyCGNS/pyCGNS#120]
* Operating System: Ubuntu 18.04
 * Python version (conda python 3.8)
 * pyCGNS version (5.3.1)
 * HDF5 version (1.12.0)

(tree, links, paths)=CGNS.MAP.load("/home/kemove/文档/data/17ms_down/cgns/LES_p_000001.cgns")
File "CGNS/MAP/EmbeddedCHLone.pyx", line 517, in CGNS.MAP.EmbeddedCHLone.load CGNS.MAP.EmbeddedCHLone.CHLoneException: (102, 'Cannot read file

**Comment by MicK7** [comment]
Can you run "cgnscheck" on the file to see if there is any problem with it ?

Otherwise before running the python script you can run the following command:
> export HDF5_USE_FILE_LOCKING="FALSE"

**Comment by ZekiFayes** [comment]
I used the cgns in the source code (demo), it yielded

(tree, links, paths) = CGNS.MAP.load("SquaredNozzle.cgns")
  File "CGNS/MAP/EmbeddedCHLone.pyx", line 517, in CGNS.MAP.EmbeddedCHLone.load
CGNS.MAP.EmbeddedCHLone.CHLoneException: (102, 'Cannot read file [SquaredNozzle.cgns]')

When I used the following command,
```
export HDF5_USE_FILE_LOCKING="FALSE"
```
it still did not work.

**Comment by ZekiFayes** [comment]
Any other thoughts?

**Comment by MicK7** [comment]
pyCGNS seems to detect that the linux file read rights are not OK.
Something is preventing it to get the access to the CGNS file.
Otherwise, maybe  the filepath contains non-ASCII code that create the error and it is not checking the correct file access.

**Comment by MicK7** [comment]
Closing since no news.
Please reopen if necessary.
