### ISSUE TITLE
windows10 CGNS.MAP.load error

### ISSUE THREAD

**Issue by chiyandetaotie** [pyCGNS/pyCGNS#123]
* Operating System (Windows 10)
 * Python version (3.7)
 * Where Python was acquired ( Anaconda on Windows)
 * pyCGNS version (5.3.1)
 * HDF5 version (1.10.6)
 
I install pyCGNS using "pip install pyCGNS" in my anaconda virtual environment.
When I run "python .\CGNS\APP\examples\MAP\load.py", It has error as flowing:

Traceback (most recent call last):
  File "D:\cgns\pyCGNSmain\CGNS\APP\examples\MAP\load.py", line 9, in <module>        
    (tree, links, paths) = CGNS.MAP.load("./data/T0.cgns", flags=CGNS.MAP.S2P_DEFAULT)
  File "CGNS\MAP\EmbeddedCHLone.pyx", line 517, in CGNS.MAP.EmbeddedCHLone.load       
CGNS.MAP.EmbeddedCHLone.CHLoneException: (102, 'Cannot read file [data/T0.cgns]')  

How can I do to solve the problem?

**Comment by chiyandetaotie** [comment]
I download the files from https://github.com/pyCGNS/pyCGNS/tree/v5.3.1,
when I run "python pyCGNS-5.3.1\CGNS\APP\examples\MAP\save.py"
It has error as follows:
Traceback (most recent call last):
  File "save.py", line 41, in <module>
    CGNS.MAP.save(filename,tree,[],CGNS.MAP.S2P_DEFAULT)
  File "CGNS\MAP\EmbeddedCHLone.pyx", line 529, in CGNS.MAP.EmbeddedCHLone.save
TypeError: save() takes exactly 2 positional arguments (4 given)

Why it happens? What should I do to solve the problem?

**Comment by poinot** [comment]
Maybe you can have a look at Python's positional ad keywords args, you have to specify the key when you use keyword args:

https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions

**Comment by chiyandetaotie** [comment]
> Maybe you can have a look at Python's positional ad keywords args, you have to specify the key when you use keyword args:
> 
> https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions

I want to know how to load a cgns file. I use  pyCGNS(5.3.1)   to run load.py , using : 
" python D:\cgns\pyCGNSmain\CGNS\APP\examples\MAP\load.py " 

the load.py is as follows:

"
#!/usr/bin/env python
#  -------------------------------------------------------------------------
#  pyCGNS.APP - Python package for CFD General Notation System - APPlicater
#  See license.txt file in the root directory of this Python module source
#  -------------------------------------------------------------------------
#
import CGNS.MAP

(tree, links, paths) = CGNS.MAP.load(filename="D:\\cgns\\pyCGNSmain\\CGNS\APP\\examples\\MAP\\data\\T0.cgns", flags=CGNS.MAP.S2P_DEFAULT)

print(tree)
print(links)

# --- last line
"

But it has error:

"
Traceback (most recent call last):
  File "D:\cgns\pyCGNSmain\CGNS\APP\examples\MAP\load.py", line 12, in <module>
    (tree, links, paths) = CGNS.MAP.load(filename="D:\\cgns\\pyCGNSmain\\CGNS\APP\\examples\\MAP\\data\\T0.cgns", flags=CGNS.MAP.S2P_DEFAULT)
  File "CGNS\MAP\EmbeddedCHLone.pyx", line 517, in CGNS.MAP.EmbeddedCHLone.load
CGNS.MAP.EmbeddedCHLone.CHLoneException: (102, 'Cannot read file [D:\\cgns\\pyCGNSmain\\CGNS\\APP\\examples\\MAP\\data/T0.cgns]')
"

How can I solve the problem?

**Comment by MicK7** [comment]
Hello,

it seems that we have a github LFS issue that lead to a corrupted "T0.cgns" file.
Could you replace T0.cgns by bump_hdf5.cgns that is located there: https://cgns.github.io/cgns-modern.github.io/current/examples.html#supportexamples ?
