### ISSUE TITLE
windows10 CGNS.NAV error

### ISSUE THREAD

**Issue by chiyandetaotie** [pyCGNS/pyCGNS#125]
* Operating System (Windows 10)
 * Python version (3.7)
 * Where Python was acquired ( Anaconda on Windows)
 * pyCGNS version (5.3.1    conda install pyCGNS )
 * HDF5 version (1.10.6)
 
I want to use CGNS.NAV module. I run "cg_look", but it has error as follows:

* "CGNS.NAV: FATAL error, cannot import qtpy.QtCore..."

How can I to use CGNS.NAV to see cgns file?

**Comment by chiyandetaotie** [comment]
I reinstall pyCGNS as d=follows:
conda install vtk
conda install PySide2
conda install qtpy
conda install pyCGNS
And I run "cg_look", it does not have error. But it couldn't load cgns file.
How can I do ?

**Comment by MicK7** [comment]
Hello,

first you should check that pyqt5 is also installed (conda install pyqt5)
Then the file you are trying to load use the old cgns ADF standard. The conversion to newer hdf5 CGNS is not supported automatically anymore.
You need to get a hdf5 file. This can be done through the cgns official package (conda install cgns)
The `cgnsconvert -h filename` command will do the adf to hdf conversion.
