### ISSUE TITLE
[MAP] After modifying the CGNS file, save it with the function CGNS.MAP.save and the value changes

### ISSUE THREAD

**Issue by willian-yz** [pyCGNS/pyCGNS#145]
To assist reproducing bugs, please include the following:
 * Operating System Windows 11
 * Python version 3.7.13
 * Anaconda on Windows
 * pyCGNS version 6.2.2
 * HDF5 version 1.12.1
 * Numpy version 1.21.6

I am a beginner and want to implement a simple function of reading out the values on the grid in a CGNS file, modifying the values, and then rewriting them.

I read in the file using CGNS.MAP.load, modified it with Numpy, and wrote it out using CGNS.MAP.save.

But there is a problem happening, the value of the saved file will change, which is why?

my code looks like this:
```python
import numpy as np
import CGNS.MAP

tree = CGNS.MAP.load(path)

#Modifying the tree's values through np.array vx

tt_memory = 0
shape_list = [(17, 165),(17, 165),(33, 233),(17, 45),(17, 21),(97, 116)]
for j in range(6):
    tt = vx[0][tt_memory:shape_list[j][0]*shape_list[j][1]+tt_memory].reshape(shape_list[j])
    tt = tt.astype(np.float32)
    tree[0][2][1][2][j][2][3][2][2][1] = tt.copy() # change values in specific meshes
    tt_memory = tt_memory + tt.shape[0]*tt.shape[1]

CGNS.MAP.save(savepath, tree[0])
```

But there's one problem, when I reread the file

tree_modify = CGNS.MAP.load(savepath)

the value in the tree_modify is not equal to the tree. I am a beginner and would like to know how to solve this problem. I would greatly appreciate it if you could answer me!

**Comment by MicK7** [comment]
Closing without user feedback.
