### ISSUE TITLE
[NAV] Coordinate value and flow variable value cannot be loaded correctly.

### ISSUE THREAD

**Issue by Wewhole** [pyCGNS/pyCGNS#147]
To assist reproducing bugs, please include the following:
 * Operating System Windows 10
 * Python version 3.8.20
 * Anaconda on Windows
 * pyCGNS 6.2.2
 * HDF5 1.14.3
 * PyQt5 5.15.9
 * vtk 9.3.0

In the tree view, the values of nodes "/CGNSTree/Base/Zone/GridCoordinates/CoordinateX (CoordinateY or CoordinateZ)" and "/CGNSTree/Base/Zone/FlowSolution-N:1/Pressure" do not appear to be loaded correctly , and the array is empty when entering the form view. The Data type is "MT".

Error #500 occurred when clicking on VTK view, and the error is as follows:
_No data or bad data for a VTK display
Cannot create VTK view_
I think this error is related to the reasons mentioned above.

**Comment by MicK7** [comment]
For the VTK part if the mesh is not structured, it will not be working.

For the other part of the issue, if the data is very big it is possible that NAV do not load it because it is over its internal threshold.

**Comment by MicK7** [comment]
Can the data be shared to reproduce the issue ?

**Comment by Wewhole** [comment]
> Can the data be shared to reproduce the issue ?

Thank you for your reply. In fact, your previous reply has answered my doubt, because my mesh is unstructured. I think you will encounter the same problem when using other unstructured mesh data.
