### ISSUE TITLE
Unable to load CGNS file (HDF5) with CGNS.NAV on linux Mint 18 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by poinot** [pyCGNS/pyCGNS#21]
When I try to load a CGNS HDF5 file with CGNS.NAV on linux Mint 18 (Ubuntu 16.04), I get this error :

(900, 'The current load operation has been aborted:', u'No such file [/tmp/hexa_nozzle.cgns.hdf]')
Load error
and into the terminal

sh: 1: cgnsconvert: not found
It seems to use cgnsconvert which is not install on my system:

$> which cgnsconvert
When I try to load this file with CGNS.MAP, none error occurs :

import CGNS.MAP as CGM
(t,l,p) = CGM.load("hexa_nozzle.cgns")

**Comment by MicK7** [comment]
see #25
