### ISSUE TITLE
NAV : load a subtree

### ISSUE THREAD

**Issue by xgarnaud** [pyCGNS/pyCGNS#26]
I use 
tmp_tree,tmp_links,tmp_paths = CGM.load(msh_fname,subtree = zpth)
with zpth = '/BASE#1/AIR_12Split10'
but I get a tree with two zones, named 
['AIR_12Split1', 'AIR_12Split10']
and AIR_12Split1 is empty

Best regards

**Comment by poinot** [comment]
probably the same as s2p_issubpath ?
should call this function at the right place

**Comment by MicK7** [comment]
I adjusted s2p_issubpath as a quick fix.
When you say "call this function at the right place", 
are you suggesting the merge of step 4 and 5 during loading ?
