### ISSUE TITLE
CHLone import failed

### ISSUE THREAD

**Issue by treetoc** [pyCGNS/pyCGNS#39]
the pyCGNS/CGNS/MAP/__init__.py contains references to EmbeddedCHLone

EmbeddedCHLone is not available (or not properly packaged) causing the the import to fail.

**Comment by VincentZhms** [comment]
I have the same problem.When I run python setup.py install,hint me：FATAL：libhdf5 not found，please check paths.But the path alway contains the file libhdf5....  And run import CGNS.MAP,appears that ModuleNotFoundError：No module named "CGNS.MAP.EmbeddedCHLone"

**Comment by MicK7** [comment]
Hello,

thanks for reporting the issue.
Can you give me a hint on wich OS the setup install is being done ?

Mickael

**Comment by poinot** [comment]
Again, can you give us a context?

- on windows/no-anaconda/source code you have to make sure the prod has all paths
- on windows/no-anaconda/installer it should work
- on windows/anaconda it should work if you make sure the build is performed with actual anaconda python

- on UNIX you have to check paths, these are detected from h5dump install path

we close the issue, you can reopen it if you have more details
