### ISSUE TITLE
CGNS.MAP.load failed

### ISSUE THREAD

**Issue by treetoc** [pyCGNS/pyCGNS#42]
The load function is not available in this module. The same is true for CGNS.MAP.save function.
This could be linked to https://github.com/pyCGNS/pyCGNS/issues/39 or some other packaging issue.

**Comment by poinot** [comment]
the is no error stack, I guess you have an import error which may cause by a by LD_LIBRARY_PATH or any env issue. Please give more details if you want it to be reopened
