### ISSUE TITLE
string formats

### ISSUE THREAD

**Issue by xgarnaud** [pyCGNS/pyCGNS#44]
Dear all,

I get a lot of errors because of the distinction between unicode and str, specially when using pyCGNS with other libraries:
- would it be complicated to have both types are accepted?
- in some cases, pyCGNS still uses str (e.g. the paths in load) --> can this be changed to unicode?

Best regards,

Xavier

**Comment by MicK7** [comment]
Supporting both types makes the code more complex and it is already complex enough !
It was tried but dropped (see commits history)

Regarding your second point, unicode should already be working for path in load. We have a clear issue if it not the case.

**Comment by xgarnaud** [comment]
Ok thanks. I ll retry with an updated version.
