### ISSUE TITLE
building MAP on windows with anaconda

### ISSUE THREAD

**Issue by xgarnaud** [pyCGNS/pyCGNS#45]
Dear pyCGNS developpers,

With my anaconda setup, I can build and use MAP with no problem. However with slightly different versions of the packages, the build works correctly but the cgns files written are unreadable (except with the same build of MAP). The files are not readable with h5py or hdfview.

I attached the libhdf5.setting files for both installs.

Do you know how to fix this issue?

Thanks,

Xavier

[libhdf5.settings.zip](https://github.com/pyCGNS/pyCGNS/files/2075057/libhdf5.settings.zip)

**Comment by MicK7** [comment]
Thanks for reporting the issue

**Comment by MicK7** [comment]
Which version of the hd5 API is used by h5py or hdfview ?
If it is API 1.8, it would make sense that they cannot load file written with 1.10 API.

**Comment by xgarnaud** [comment]
Thanks for your help.

Indeed, the files can be read with h5py if built with hdf5 v1.10, not with h5py if built with hdf5 v1.8. 

There is no problem with MAP!

**Comment by xgarnaud** [comment]
There might still be an issue with MAP...

Even with hdf5 1.10, if I use h5py to write the cgns file, it can be read with all the tools (paraview, cgnsview, cassiopee, ...)

**Comment by MicK7** [comment]
MAP is validated for hdf5 with 1.8 API.

Compatibility with hdf5 1.10 is still a work in progress. 
You may need to use the h5repack tool with 1.10.
For next release hdf5 1.10.2 will be targeted.

**Comment by xgarnaud** [comment]
Thank you for your help.
