### ISSUE TITLE
MAP: data shape with flags = CGM.NODATA

### ISSUE THREAD

**Issue by xgarnaud** [pyCGNS/pyCGNS#46]
Dear all,

When I load a tree without NODATA, I get zone data of shape (1,3). If I use flags = CGM.NODATA (maxdata = 64) I get the same data with shape (3,1).
Do you have the same thing?

Xavier

**Comment by MicK7** [comment]
Hello,

It seems you are not using the appropriate flags.
To load a tree with NODATA, you shoud do:

flags = CGM.DEFAULT | CGM.NODATA

and add the maxdata.
Without the CGM.DEFAULT flag properly set, array will be loaded as C numpy arrays.

The documentation on how to use flags may need a rework.

**Comment by xgarnaud** [comment]
Ok thanks!
