### ISSUE TITLE
[NAV] Error #0 "Cannot change name of node" when just double-clicking a node without modification

### ISSUE THREAD

**Issue by picost** [pyCGNS/pyCGNS#49]
When using CGNS NAV to edit a tree, entering and leaving edition mode of any node name without performing any modification triggers an error with message:

```
The new name [<node name>] is rejected
Cannot change name of node: <node path>
```

PyCGNS-5.0.565, Python 2.7.13, CentOS 7

**Comment by MicK7** [comment]
Thanks for reporting. 
This error may be linked to #48 . NAV is not fully stable for python 2.7 right now.
If using python 3 is possible please do.

**Comment by MicK7** [comment]
Thanks for reporting.
We will add a check to verify is the nodename is unchanged.
