### ISSUE TITLE
Provide conda-ready package

### ISSUE THREAD

**Issue by poinot** [pyCGNS/pyCGNS#50]
Anaconda Windows/Unix and Python 2/3

- with Anaconda3 would have to deal with HDF5 1.10 :(

**Comment by MicK7** [comment]
Recent commit may have improved the situation.
Now settings are identical to h5py when compiling with HDF5 1.10 and should allow writting of compatible file with 1.8 version. Performance may be reduced.

**Comment by MicK7** [comment]
see: https://github.com/MicK7/my_conda_recipes/blob/master/pycgns/meta.yaml

**Comment by gcardozo123** [comment]
Are you going to publish this recipe on  Conda-Forge?

**Comment by poinot** [comment]
AFAIK there's no work on this topic today.
But we have to do it...
