### ISSUE TITLE
PyQT5 uses its own sip module

### ISSUE THREAD

**Issue by poinot** [pyCGNS/pyCGNS#88]
With a PyQt5, sip is build with module option: --sip-module PyQt5.sip

Add a try/except on import for sip in cg_look

**Comment by MicK7** [comment]
sip may be uneeded because PyQt5 API is directly using the good QString
According to PyQt5 website a simple fix for backward compatibility is to write.

`from PyQt5 import QtCore; import sip`

but it seems that qtpy may already be doing the job in its own __init__.py

**Comment by MicK7** [comment]
Closing, reopen if a similar bug happens with pySide6
