### ISSUE TITLE
running tox changes CGNS/MAP/CHLone_config.h [MAP]

### ISSUE THREAD

**Issue by arthurzenika** [pyCGNS/pyCGNS#99]
To assist reproducing bugs, please include the following:
 * Operating System : Ubuntu 18.04
 * Python version 3.6.9
 * Where Python was acquired : system Python (via tox)
 * pyCGNS version: 5.1
 * HDF5 version: 1.10.0

After running tox on my local machine, I get the following diff : 

```
git diff
diff --git a/CGNS/MAP/CHLone_config.h b/CGNS/MAP/CHLone_config.h
index a6dd4843..ec0921b3 100644
--- a/CGNS/MAP/CHLone_config.h
+++ b/CGNS/MAP/CHLone_config.h
@@ -7,7 +7,7 @@
 */
 #define CHLONE_ON_WINDOWS 0
 #define CHLONE_H5CONF_STD 1
-#define CHLONE_H5CONF_64  0
+#define CHLONE_H5CONF_64  1
 #define CHLONE_H5CONF_UP  1
 
 #include <stdarg.h>
```

Should there be a way for this file (or a copy of this file) to be ignored by .gitignore ?

**Comment by MicK7** [comment]
You are right, this file should not even be versionned by git.
I think that it was added for convenience and to not regenerate the file at each compilation. (TBC)
